# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04a659661d3dbc51f8ccc24eaf93a5d2a678ab2320aeff4b76d6fb9e9d452c0ed4029185da0317dfaf6ce120fa4e0b5133a52cb604054ba15dddbea48cc5e6b0

test:
  secret_key_base: ed8de0392cc34f2deb9160084f9e773e739b0fb3f8465aaab283b934d3972abb3bd49222462a0db1bdcbeeecbefc0b66f0d235a034394546228a57c09f987599

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
